name: ci

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: sed -i 's/ssh:/https:/g' ./packages/rlogin-dcent-provider/package-lock.json # avoid issue caused by using ssh from github actions
    - run: npm i
    - run: npm run setup
    - run: npm run build
    - run: npm run test
    - run: npm run lint
    - run: npx lerna exec -- npm publish --dry-run
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
